### ISSUE TITLE
use hardnet as the local feature extractor

### ISSUE THREAD

**Issue by yhethanchen** [DagnyT/hardnet#14]
Hi, I try to use hardnet to replace SIFT as the local feature extractor for landmark recognition.
But I got a worse results than SIFT.
Here is my pipeline:
(1) Use SIFT key point detector implemented by openCV to get the location and diamater of key points.
(2) sample a patch according to the diameter for each key point an resize it to 32x32.
(For example, for a key point with with diameter 15, I sample 15x15 patch and then resize it to 32x32)
(3) use hardnet to extract 128-dimensional feature

For step 2, I found that the diameter of most key points are pretty small (<8 pixels), I suspect this is the reason why hardnet feature perform worse. 

Do I need to always sample 32x32 patch for each key point instead of using the diameter of the key point? Thanks for answering :).

**Comment by ducha-aiki** [comment]
@yhethanchen 
Your pipeline seems correct except two things. 
1) "Diameter" is actually "radius", so if you get 15, then you should extract 30x30 and resize to 32x32.
2) Moreover, internally in SIFT implementation, patch used for description is 3..5 times bigger than this radius. E.g., see this source code
https://github.com/opencv/opencv_contrib/blob/master/modules/xfeatures2d/src/sift.cpp#L192

> // determines the size of a single descriptor orientation histogram
> static const float SIFT_DESCR_SCL_FCTR = 3.f;
> 
Also, see in the local feature for landmarks paper, coefficient here is 3 sqrt(3): 
![image](https://user-images.githubusercontent.com/4803565/39699886-6ed10a24-51fb-11e8-98ea-ef271e65272a.png)
http://cmp.felk.cvut.cz/~matas/papers/perdoch-geometry-cvpr09.pdf
And here is from source code in the same paper:

>   desc_factor = 3.0f*sqrt(3.0f);

https://github.com/perdoch/hesaff/blob/master/hesaff.cpp#L32

So, sure HardNet is performing worse, because it is performing on patches, which are 2*(3..3sqrt3) = 6..10 times smaller, than SIFT. Bigger the patch - more information.

**Comment by yhethanchen** [comment]
Thank you so much for you quick reply, I will try it again :).

**Comment by ducha-aiki** [comment]
@yhethanchen you can try this thing https://github.com/ducha-aiki/mods-light-zmq
It extracts Hessian keypoints with HardNet and is much better than SIFT

**Comment by hurricane2018** [comment]
Two questions:

1. So how large should the patch be ? Is 64 X 64 enough ?

2. For example, if the patch size is 64 X 64, the input of the hardnet is only 32 X 32. How do you handle this issue ? Do you resize the patch ?

**Comment by ducha-aiki** [comment]
@hurricane2018 patch "size" in pixels is irrelevant here. I recommend you to read original SIFT paper, or any other similar about local features.  https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf

But I will try to explain how local features work here and what I mean by scale
. To detect local interest points, usually you have some function, which reliably localize some patterns in image. E.g., Hessian detector, which is determinant of Hessian matrix == matrix of 2nd spatial derivatives. Of difference of Gaussians aka SIFT detector. Or corners. Or whatever you have. Let is be detector Det.
 
One very important thing here is the detector fires == works best with patterns of fixed size. For Hessian it is 3x3 pixel neighborhood. So all it does - says is there a blob of radius 1 (one!) pixel, or not. But do this very reliably. 

But 3x3 patch is really small and not discriminative. Moreover, you already know, that it is a blob and all blobs are similar. To get local descriptor, you multiply this 3x3 neighborhood by so called "measurement region scale" - that is set to 3..5 usually and which I have mentioned about. 

Now  you have patch, which is 3..5 * (3x3) = 9x9 ... 15x15.  Then you rescale it to fixed size, usually 41x41 for SIFT, or 32x32 for HardNet. and apply your descriptor function. 

But...so far we can detect only blobs of radius 1 == 3x3 neighborhood. What if we have bigger blobs in image? 
For this there is so called scale-pyramid. You blur and downscale the image and apply the same procedure of detecting 1-pixels-radius blobs. But in downscaled image. Corresponding region in original image will be bigger. And the proportion of size of this downscaled image to our original one is the keypoint scale, e.g. in OpenCV here https://docs.opencv.org/3.2.0/d2/d29/classcv_1_1KeyPoint.html#a308006c9f963547a8cff61548ddd2ef2

So to get the proper patch for the keypoint, you take keypoint scale from detector, multiply by 3..5 and get radius of the patch, which you need to extract. Because they all will be different, you rescale to 32x32. And then apply HardNet. Btw, it is all implemented in link above. 

Hope, this helps.

**Comment by ducha-aiki** [comment]
@hurricane2018 And you if refer to already pre-extracted patch-datasets like Brown 
http://phototour.cs.washington.edu/patches/default.htm
or PS https://github.com/rmitra/PS-Dataset
or HPatches https://hpatches.github.io/ then all this works already done. All you need then is to take ready-patch and resize it to 32x32

**Comment by yhethanchen** [comment]
@ducha-aiki . It is so nice of you to provide so much useful information :). 
By the way, by using the scaling factor you provided, I got a better result, thank you so much again!

**Comment by hurricane2018** [comment]
@yhethanchen  Could you share the code with me ?
